# Generated by Django 4.2.11 on 2026-01-08 14:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название системы')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('srd_url', models.URLField(blank=True, verbose_name='Ссылка на SRD')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Игровая система',
                'verbose_name_plural': 'Игровые системы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название сценария')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Текст сценария')),
                ('difficulty', models.CharField(choices=[('beginner', 'Новичок (1-3 уровень)'), ('intermediate', 'Опытный (4-10 уровень)'), ('advanced', 'Ветеран (11-16 уровень)'), ('expert', 'Мастер (17-20 уровень)')], default='intermediate', max_length=20, verbose_name='Уровень сложности')),
                ('estimated_play_time', models.PositiveIntegerField(default=4, verbose_name='Примерное время игры (часы)')),
                ('recommended_players', models.PositiveIntegerField(default=4, verbose_name='Рекомендуемое количество игроков')),
                ('recommended_level', models.CharField(default='1-3', max_length=50, verbose_name='Рекомендуемый уровень персонажей')),
                ('combat_balance_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Оценка баланса боя')),
                ('puzzle_complexity_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Сложность загадок')),
                ('narrative_coherence', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Связность повествования')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный доступ')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Теги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликован')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('favorites', models.PositiveIntegerField(default=0, verbose_name='В избранном')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('game_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.gamesystem', verbose_name='Игровая система')),
            ],
            options={
                'verbose_name': 'Сценарий',
                'verbose_name_plural': 'Сценарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('experience_level', models.CharField(choices=[('beginner', 'Новичок (1-3 уровень)'), ('intermediate', 'Опытный (4-10 уровень)'), ('advanced', 'Ветеран (11-16 уровень)'), ('expert', 'Мастер (17-20 уровень)')], default='intermediate', max_length=20, verbose_name='Уровень опыта')),
                ('show_advanced_analytics', models.BooleanField(default=True, verbose_name='Показывать расширенную аналитику')),
                ('receive_notifications', models.BooleanField(default=True, verbose_name='Получать уведомления')),
                ('scenarios_created', models.PositiveIntegerField(default=0, verbose_name='Создано сценариев')),
                ('scenarios_published', models.PositiveIntegerField(default=0, verbose_name='Опубликовано сценариев')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='Всего просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('favorite_systems', models.ManyToManyField(blank=True, to='core.gamesystem', verbose_name='Любимые системы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.scenario', verbose_name='Сценарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('combat_balance', 'Баланс боев'), ('puzzle_analysis', 'Анализ загадок'), ('narrative_flow', 'Поток повествования'), ('element_extraction', 'Извлечение элементов'), ('recommendations', 'Рекомендации')], max_length=50, verbose_name='Тип анализа')),
                ('results', models.JSONField(default=dict, verbose_name='Результаты анализа')),
                ('recommendations', models.JSONField(blank=True, default=list, verbose_name='Рекомендации')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='Предупреждения')),
                ('execution_time', models.FloatField(default=0.0, verbose_name='Время выполнения (сек)')),
                ('confidence_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Уверенность анализа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('analysis_version', models.CharField(default='1.0', max_length=50, verbose_name='Версия анализатора')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='core.scenario', verbose_name='Сценарий')),
            ],
            options={
                'verbose_name': 'Результат анализа',
                'verbose_name_plural': 'Результаты анализа',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('npc', 'NPC (Неигровой персонаж)'), ('location', 'Локация'), ('item', 'Предмет'), ('encounter', 'Боевая встреча'), ('puzzle', 'Загадка/Головоломка'), ('trap', 'Ловушка'), ('treasure', 'Сокровище'), ('clue', 'Зацепка/Подсказка'), ('event', 'Событие'), ('dialogue', 'Диалог')], max_length=20, verbose_name='Тип элемента')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_position', models.PositiveIntegerField(verbose_name='Начальная позиция в тексте')),
                ('end_position', models.PositiveIntegerField(verbose_name='Конечная позиция в тексте')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='Атрибуты')),
                ('challenge_rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Уровень сложности (CR)')),
                ('xp_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='Опыт за победу')),
                ('gold_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость в золотых')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('related_elements', models.ManyToManyField(blank=True, to='core.scenarioelement', verbose_name='Связанные элементы')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='core.scenario', verbose_name='Сценарий')),
            ],
            options={
                'verbose_name': 'Элемент сценария',
                'verbose_name_plural': 'Элементы сценария',
                'ordering': ['start_position'],
                'indexes': [models.Index(fields=['scenario', 'element_type'], name='core_scenar_scenari_4c8386_idx'), models.Index(fields=['element_type', 'challenge_rating'], name='core_scenar_element_a0153b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['status', 'is_public'], name='core_scenar_status_6d50e3_idx'),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['game_system', 'difficulty'], name='core_scenar_game_sy_7bbbcd_idx'),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['created_at'], name='core_scenar_created_8cfd5c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'scenario')},
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['scenario', 'analysis_type'], name='core_analys_scenari_849591_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['created_at'], name='core_analys_created_39183a_idx'),
        ),
    ]
